services:
  pg:
    image: postgres:16-alpine
    ports:
      - "6008:5432"
    environment:
    - POSTGRES_USER=albqvxc
    - POSTGRES_PASSWORD=lexsa
    - POSTGRES_DB=portfolio
    volumes:
     - portfolio-volume:/var/lib/postgresql/data
    restart: always
  api:
    build: .
    ports:
      - "3303:8001"
    environment:
      - DATABASE_URL=postgres://albqvxc:lexsa@pg:5432/portfolio?sslmode=disable
    depends_on:
      - pg
    restart: always

volumes:
  portfolio-volume:
