services:
  pg:
    image: postgres:16-alpine
    ports:
      - "6008:5432"
    environment:
    - POSTGRES_USER=albqvxc
    - POSTGRES_PASSWORD=lexsa
    - POSTGRES_DB=portfolio
    volumes:
     - portfolio-volume:/var/lib/postgresql/data
  api:
    build: .
    ports:
      - "3333:3333"
    environment:
      - DATABASE_URL=postgres://albqvxc:lexsa@pg:5432/portfolio?sslmode=disable
    depends_on:
      - pg

volumes:
  portfolio-volume:
