@baseUrl = http://localhost:3333

POST {{baseUrl}}/categories
Content-Type: application/json

{
  "name": "Full-Stack"
}

###
GET {{baseUrl}}/categories

###
GET {{baseUrl}}/categories/1

###
DELETE {{baseUrl}}/categories/1



