@baseUrl = http://localhost:3333

GET {{baseUrl}}/health

###
POST {{baseUrl}}/projects
Content-Type: application/json

{
  "name": "salve project",
  "github_url": "salve",
  "demo_url": "salve",
  "is_pinned": true
}
