@baseUrl = http://localhost:3333

GET {{baseUrl}}/health

### Create Project
POST {{baseUrl}}/projects
Content-Type: application/json

{
  "name": "bom dia meus projetosss",
  "github_url": "https://github.com/albqvictor1508/plush-api",
  "category_id": 6,
  "description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset shee",
  "is_pinned": true,
  "technologies": [
    {"id": 3},
    {"id": 4}
  ]
}

### Get Projects
GET {{baseUrl}}/projects

### Update Projects
PUT {{baseUrl}}/projects/8
Content-Type: application/json

{
  "name": "testeeeee",
  "github_url": "https://github.com/albqvictor1508/plush-api",
  "category_id": 5,
  "description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset shee",
  "is_pinned": true
}

### Update Projects
DELETE {{baseUrl}}/projects/6

### Get Project By ID
GET {{baseUrl}}/projects/8

