@baseUrl = http://localhost:3333

POST {{baseUrl}}/technologies
Content-Type: application/json

{
  "name": "Golang",
  "photo_url": "https://duckduckgo.com/?t=ffab&q=golang&ia=images&iax=images&iai=https%3A%2F%2Fmillennia-solusi.id%2Fwp-content%2Fwebp-express%2Fwebp-images%2Fuploads%2F2022%2F09%2Fgolang-1.png.webp"
}

###
GET {{baseUrl}}/technologies

###
GET {{baseUrl}}/technologies/1

###
DELETE {{baseUrl}}/technologies/1

###
PUT {{baseUrl}}/technologies/1

